import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillInstagram, AiFillLinkedin, AiFillGithub } from 'react-icons/ai';
import Image from 'next/image';
import profile from '../public/profile.jpg';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import web7 from '../public/web7.png';
import web8 from '../public/web8.png';
import web9 from '../public/web9.png';
import web10 from '../public/web10.png';
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title className="dark:text-white">Yehezkiel Owen Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 font-poppins dark:bg-slate-900 dark:text-white transition-all duration-300">
        <section className="md:container mx-auto xl:px-60 mb-20">
          <nav className="py-10 mb-112 flex justify-between">
            <h1 className="text-xl font-burtons uppercase">Yehezkiel Owen</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  href="https://www.linkedin.com/in/yehezkiel-owen-ombuh-018459251/"
                  target="_blank"
                  rel="noreferrer"
                  className="bg-gradient-to-r from-rose-500 to-rose-700 text-white px-4 py-2 rounded-md ml-8"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="relative mx-auto rounded-full w-80 h-80 overflow-hidden my-10">
            <Image
              src={profile}
              alt="Profile Picture"
              fill
              className="object-cover"
            />
          </div>
          <div className="text-center p-0">
            <h2 className="text-5xl py-2 text-rose-700 font-medium">
              Yehezkiel Owen
            </h2>
            <h3 className="text-2xl font-medium py-2">
              Web developer and designer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-500">
              I am a web developer and designer based in Indonesia. I have a
              passion for creating beautiful and functional websites.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <a
              href="https://www.instagram.com/sitouxz/"
              target="_blank"
              rel="noreferrer"
            >
              <AiFillInstagram />
            </a>
            <a
              href="https://www.linkedin.com/in/yehezkiel-owen-ombuh-018459251/"
              target="_blank"
              rel="noreferrer"
            >
              <AiFillLinkedin />
            </a>
            <a
              href="https://github.com/Sitouxz"
              target="_blank"
              rel="noreferrer"
            >
              <AiFillGithub />
            </a>
          </div>
        </section>

        <section className="md:container mx-auto xl:px-60 mb-20">
          <div className="mb-3">
            <h3 className="text-3xl py-1">Talk about</h3>
            <p>
              Currently studying at{' '}
              <span className="text-rose-500 font-bold">Klabat University</span>{' '}
              and gaining more experience through personal projects.
            </p>
          </div>
          <div className="mb-3">
            <h2 className="text-xl py-1">Interests</h2>
            <p>
              <span className="dark:bg-red-900 bg-red-100 px-1"> 🖼️UI/UX </span>
              <span className="dark:bg-yellow-900 bg-yellow-100 px-1">
                {' '}
                👨‍💻Code/JavaScript{' '}
              </span>
              <span className="dark:bg-green-900 bg-green-100 px-1">
                {' '}
                📚Tech Stack/MERN{' '}
              </span>
              <span className="dark:bg-blue-900 bg-blue-100 px-1">
                {' '}
                ✨Logo Design{' '}
              </span>
            </p>
          </div>
          <div>
            <h2 className="text-xl py-1">Tools I use</h2>
            <span className="text-red-500">Visual Studio Code</span>
            <br />
            <span className="text-red-500">Git</span>
            <br />
            <span className="text-red-500">NPM</span>
            <br />
            <span className="text-blue-500">Trello</span>
            <br />
            <span className="text-amber-500">Adobe Illustrator</span>
            <br />
            <span className="text-amber-500">Figma</span>
          </div>
        </section>
        <section className="md:container mx-auto xl:px-60">
          <div className="mb-3">
            <h3 className="text-3xl py-1">Portfolio</h3>
            <p className="mb-3">
              Since I started my journey as a developer and designer, I have
              worked on a wide range of projects.
            </p>
            <p>
              br I offer a wide range of services, including Web Design, Web
              Development, UI/UX and everything in between. Here are some of
              them.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                src={web1}
                alt="web1"
                className="rounded-lg object-cover shadow-lg"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web2}
                alt="web2"
                className="rounded-lg object-cover shadow-lg"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web3}
                alt="web3"
                className="rounded-lg object-cover shadow-lg"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web4}
                alt="web4"
                className="rounded-lg object-cover shadow-lg"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web5}
                alt="web5"
                className="rounded-lg object-cover shadow-lg"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web6}
                alt="web6"
                className="rounded-lg object-cover shadow-lg"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web7}
                alt="web7"
                className="rounded-lg object-cover shadow-lg"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web8}
                alt="web8"
                className="rounded-lg object-cover shadow-lg"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web9}
                alt="web9"
                className="rounded-lg object-cover shadow-lg"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web10}
                alt="web10"
                className="rounded-lg object-cover shadow-lg"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
