import Head from 'next/head';
import { BsFillMoonStarsFill } from 'react-icons/bs';
import { AiFillInstagram, AiFillLinkedin, AiFillGithub } from 'react-icons/ai';
import Image from 'next/image';
import profile from '../public/profile.jpg';
import web1 from '../public/web1.png';
import web2 from '../public/web2.png';
import web3 from '../public/web3.png';
import web4 from '../public/web4.png';
import web5 from '../public/web5.png';
import web6 from '../public/web6.png';
import web7 from '../public/web7.png';
import web8 from '../public/web8.png';
import web9 from '../public/web9.png';
import web10 from '../public/web10.png';
import web11 from '../public/web11.png';
import web12 from '../public/web12.png';
import web13 from '../public/web13.png';
import web14 from '../public/web14.png';
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title className='dark:text-white'>Yehezkiel Owen Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='px-10 transition-all duration-300 bg-white font-poppins dark:bg-slate-900 dark:text-white'>
        <section className='mx-auto mb-20 md:container xl:px-60'>
          <nav className='flex justify-between py-10 mb-112'>
            <h1 className='text-xl uppercase font-burtons'>Yehezkiel Owen</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className='text-2xl cursor-pointer'
                />
              </li>
              <li>
                <a
                  href='https://www.linkedin.com/in/yehezkiel-owen-ombuh-018459251/'
                  target='_blank'
                  rel='noreferrer'
                  className='px-4 py-2 ml-8 text-white rounded-md bg-gradient-to-r from-rose-500 to-rose-700'>
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className='relative mx-auto my-10 overflow-hidden rounded-full w-80 h-80'>
            <Image
              src={profile}
              alt='Profile Picture'
              fill
              className='object-cover'
            />
          </div>
          <div className='p-0 text-center'>
            <h2 className='py-2 text-5xl font-medium text-rose-700'>
              Yehezkiel Owen
            </h2>
            <h3 className='py-2 text-2xl font-medium'>
              Web developer and designer.
            </h3>
            <p className='py-5 leading-8 text-gray-800 text-md dark:text-gray-500'>
              I&apos;m a passionate web developer and designer with over 2 years
              of hands-on experience in front-end and back-end development.
              Currently pursuing a Bachelor&apos;s degree in Computer Science at
              Klabat University, and actively involved in real-world projects at
              Formulatrix, FXMedia Singapore, and more. I love turning ideas
              into functional, user-friendly digital products — combining
              beautiful design with clean, scalable code.
            </p>
          </div>
          <div className='flex justify-center gap-16 py-3 text-5xl text-gray-600'>
            <a
              href='https://www.instagram.com/sitouxz/'
              target='_blank'
              rel='noreferrer'>
              <AiFillInstagram />
            </a>
            <a
              href='https://www.linkedin.com/in/yehezkiel-owen-ombuh-018459251/'
              target='_blank'
              rel='noreferrer'>
              <AiFillLinkedin />
            </a>
            <a
              href='https://github.com/Sitouxz'
              target='_blank'
              rel='noreferrer'>
              <AiFillGithub />
            </a>
          </div>
        </section>

        <section className='mx-auto mb-20 md:container xl:px-60'>
          <div className='mb-3'>
            <h3 className='py-1 text-3xl'>Talk about</h3>
            <p>
              🚀 Currently working on FLO i8 at Formulatrix, focusing on
              performance optimization, UI enhancements, and collaborative
              feature development. 🎓 Balancing professional experience with
              academic growth to stay sharp and innovative.
            </p>
          </div>
          <div className='mb-3'>
            <h2 className='py-1 text-xl'>Interests</h2>
            <p>
              <span className='px-1 bg-red-100 dark:bg-red-900'>
                🖼️ UI/UX Design
              </span>
              <span className='px-1 bg-yellow-100 dark:bg-yellow-900'>
                👨‍💻 JavaScript & TypeScript
              </span>
              <span className='px-1 bg-green-100 dark:bg-green-900'>
                📚 MERN Stack & Web Architecture
              </span>
              <span className='px-1 bg-blue-100 dark:bg-blue-900'>
                ✨ Clean Code & Design Systems
              </span>
              <span className='px-1 bg-blue-100 dark:bg-pink-900'>
                🎨 Logo Design & Visual Branding
              </span>
            </p>
          </div>
          <div>
            <h2 className='py-1 text-xl'>Tools I use</h2>
            <span className='text-red-500'>Visual Studio Code</span>
            <br />
            <span className='text-red-500'>Git & GitHub</span>
            <br />
            <span className='text-red-500'>NPM</span>
            <br />
            <span className='text-red-500'>Yarn</span>
            <br />
            <span className='text-blue-500'>Trello</span>
            <br />
            <span className='text-amber-500'>Adobe Illustrator</span>
            <br />
            <span className='text-amber-500'>Figma</span>
            <br />
            <span className='text-amber-500'>Postman, MongoDB Compass</span>
            <br />
            <span className='text-amber-500'>GCP, Vercel, Netlify</span>
          </div>
        </section>
        <section className='mx-auto md:container xl:px-60'>
          <div className='mb-3'>
            <h3 className='py-1 text-3xl'>Portfolio</h3>
            <p className='mb-3'>
              Since I started my journey as a developer and designer, I have
              worked on a wide range of projects.
            </p>
            <p>
              Here are some of the projects I&apos;ve worked on professionally
              and independently:
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='flex-1 basis-1/3'>
              <Image
                src={web1}
                alt='web1'
                className='object-cover rounded-lg shadow-lg'
              />
            </div>
            <div className='flex-1 basis-1/3'>
              <Image
                src={web2}
                alt='web2'
                className='object-cover rounded-lg shadow-lg'
              />
            </div>
            <div className='flex-1 basis-1/3'>
              <Image
                src={web3}
                alt='web3'
                className='object-cover rounded-lg shadow-lg'
              />
            </div>
            <div className='flex-1 basis-1/3'>
              <Image
                src={web4}
                alt='web4'
                className='object-cover rounded-lg shadow-lg'
              />
            </div>
            <div className='flex-1 basis-1/3'>
              <Image
                src={web5}
                alt='web5'
                className='object-cover rounded-lg shadow-lg'
              />
            </div>
            <div className='flex-1 basis-1/3'>
              <Image
                src={web6}
                alt='web6'
                className='object-cover rounded-lg shadow-lg'
              />
            </div>
            <div className='flex-1 basis-1/3'>
              <Image
                src={web7}
                alt='web7'
                className='object-cover rounded-lg shadow-lg'
              />
            </div>
            <div className='flex-1 basis-1/3'>
              <Image
                src={web8}
                alt='web8'
                className='object-cover rounded-lg shadow-lg'
              />
            </div>
            <div className='flex-1 basis-1/3'>
              <Image
                src={web9}
                alt='web9'
                className='object-cover rounded-lg shadow-lg'
              />
            </div>
            <div className='flex-1 basis-1/3'>
              <Image
                src={web10}
                alt='web10'
                className='object-cover rounded-lg shadow-lg'
              />
            </div>
            <div className='flex-1 basis-1/3'>
              <Image
                src={web11}
                alt='web11'
                className='object-cover rounded-lg shadow-lg'
              />
            </div>
            <div className='flex-1 basis-1/3'>
              <Image
                src={web12}
                alt='web12'
                className='object-cover rounded-lg shadow-lg'
              />
            </div>
            <div className='flex-1 basis-1/3'>
              <Image
                src={web13}
                alt='web13'
                className='object-cover rounded-lg shadow-lg'
              />
            </div>
            <div className='flex-1 basis-1/3'>
              <Image
                src={web14}
                alt='web14'
                className='object-cover rounded-lg shadow-lg'
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
